<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latestmajor</LangVersion>
    <Version>1.1.0</Version>
    <Authors>alevdikov</Authors>
    <PackageProjectUrl>https://github.com/alevdikov/GenericFilters</PackageProjectUrl>
    <PackageLicense>http://www.apache.org/licenses/LICENSE-2.0</PackageLicense>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RepositoryUrl>https://github.com/alevdikov/GenericFilters</RepositoryUrl>
    <Description>
    A powerful and extensible filtering framework for C# applications. 
    GenericFilters enables dynamic, attribute-driven filtering logic for LINQ queries, in-memory collections, and Cosmos DB SDK queries.
    </Description>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LinqKit.Core" Version="1.2.8" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GenericFilters.Tests" />
  </ItemGroup>

</Project>
