-- Insert categories
INSERT INTO Categories (CategoryId, Name) VALUES (1, 'Electronics');
INSERT INTO Categories (CategoryId, Name) VALUES (2, 'Books');
INSERT INTO Categories (CategoryId, Name) VALUES (3, 'Clothing');
INSERT INTO Categories (CategoryId, Name) VALUES (4, 'Home & Kitchen');
INSERT INTO Categories (CategoryId, Name) VALUES (5, 'Toys');

-- Insert products
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (1, 1, 'Electronics Product 1', 'Limited edition item.', 53.61, 24, '2025-10-24', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (2, 1, 'Electronics Product 2', 'Customer favorite product.', 139.27, 67, '2025-08-07', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (3, 1, 'Electronics Product 3', 'Limited edition item.', 321.3, 40, '2025-12-27', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (4, 1, 'Electronics Product 4', 'Limited edition item.', 488.56, 74, '2025-05-13', '2025-05-18');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (5, 1, 'Electronics Product 5', 'Limited edition item.', 144.27, 23, '2025-09-17', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (6, 1, 'Electronics Product 6', 'Limited edition item.', 56.7, 44, '2025-10-17', '2025-11-11');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (7, 1, 'Electronics Product 7', 'Best in class performance.', 448.36, 80, '2025-08-05', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (8, 1, 'Electronics Product 8', 'Best in class performance.', 84.02, 34, '2025-10-09', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (9, 1, 'Electronics Product 9', 'Best in class performance.', 61.85, 56, '2025-09-23', '2025-11-18');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (10, 1, 'Electronics Product 10', 'Customer favorite product.', 94.9, 92, '2025-03-11', '2025-05-24');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (11, 2, 'Books Product 1', 'Limited edition item.', 185.23, 72, '2025-11-11', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (12, 2, 'Books Product 2', 'Best in class performance.', 56.04, 89, '2025-10-06', '2025-12-15');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (13, 2, 'Books Product 3', 'Limited edition item.', 150.34, 98, '2025-12-14', '2026-02-27');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (14, 2, 'Books Product 4', 'Limited edition item.', 326.98, 80, '2025-12-08', '2026-02-22');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (15, 2, 'Books Product 5', 'Limited edition item.', 309.71, 31, '2025-05-23', '2025-08-01');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (16, 2, 'Books Product 6', 'Best in class performance.', 390.88, 60, '2025-11-06', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (17, 2, 'Books Product 7', 'Customer favorite product.', 269.04, 84, '2025-08-13', '2025-08-20');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (18, 2, 'Books Product 8', 'Limited edition item.', 164.05, 29, '2025-04-20', '2025-06-23');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (19, 2, 'Books Product 9', 'Customer favorite product.', 321.64, 69, '2025-10-17', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (20, 2, 'Books Product 10', 'Best in class performance.', 262.41, 40, '2025-04-12', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (21, 3, 'Clothing Product 1', 'Best in class performance.', 64.14, 37, '2025-02-17', '2025-03-11');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (22, 3, 'Clothing Product 2', 'Best in class performance.', 286.08, 45, '2025-04-08', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (23, 3, 'Clothing Product 3', 'Customer favorite product.', 411.38, 75, '2025-06-16', '2025-06-25');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (24, 3, 'Clothing Product 4', 'Best in class performance.', 36.1, 17, '2025-12-12', '2026-01-06');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (25, 3, 'Clothing Product 5', 'Best in class performance.', 370.23, 44, '2025-06-06', '2025-07-25');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (26, 3, 'Clothing Product 6', 'Limited edition item.', 261.29, 22, '2025-11-12', '2026-01-21');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (27, 3, 'Clothing Product 7', 'Customer favorite product.', 292.44, 24, '2025-09-07', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (28, 3, 'Clothing Product 8', 'Customer favorite product.', 220.43, 99, '2025-03-22', '2025-06-15');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (29, 3, 'Clothing Product 9', 'Best in class performance.', 330.11, 10, '2025-11-21', '2026-02-17');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (30, 3, 'Clothing Product 10', 'Best in class performance.', 385.18, 81, '2025-05-04', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (31, 4, 'Home & Kitchen Product 1', 'Customer favorite product.', 147.28, 10, '2025-09-28', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (32, 4, 'Home & Kitchen Product 2', 'Customer favorite product.', 198.31, 67, '2025-08-18', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (33, 4, 'Home & Kitchen Product 3', 'Customer favorite product.', 109.33, 97, '2025-06-20', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (34, 4, 'Home & Kitchen Product 4', 'Best in class performance.', 426.1, 41, '2025-04-09', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (35, 4, 'Home & Kitchen Product 5', 'Customer favorite product.', 441.22, 42, '2025-06-07', '2025-08-09');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (36, 4, 'Home & Kitchen Product 6', 'Best in class performance.', 181.02, 64, '2025-03-01', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (37, 4, 'Home & Kitchen Product 7', 'Best in class performance.', 444.05, 78, '2025-08-13', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (38, 4, 'Home & Kitchen Product 8', 'Limited edition item.', 347.67, 100, '2025-06-18', '2025-08-19');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (39, 4, 'Home & Kitchen Product 9', 'Customer favorite product.', 328.63, 32, '2025-12-19', '2026-01-09');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (40, 4, 'Home & Kitchen Product 10', 'Customer favorite product.', 256.78, 58, '2025-03-27', '2025-06-12');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (41, 5, 'Toys Product 1', 'Best in class performance.', 39.02, 100, '2025-01-25', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (42, 5, 'Toys Product 2', 'Limited edition item.', 53.81, 59, '2025-05-02', '2025-05-24');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (43, 5, 'Toys Product 3', 'Limited edition item.', 153.24, 100, '2025-12-13', '2026-03-12');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (44, 5, 'Toys Product 4', 'Limited edition item.', 239.13, 23, '2025-02-06', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (45, 5, 'Toys Product 5', 'Limited edition item.', 489.45, 96, '2025-03-09', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (46, 5, 'Toys Product 6', 'Limited edition item.', 77.22, 29, '2025-02-25', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (47, 5, 'Toys Product 7', 'Best in class performance.', 40.32, 49, '2025-06-26', '2025-08-07');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (48, 5, 'Toys Product 8', 'Limited edition item.', 392.0, 77, '2025-05-21', NULL);
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (49, 5, 'Toys Product 9', 'Best in class performance.', 53.89, 90, '2025-02-09', '2025-02-13');
INSERT INTO Products (ProductId, CategoryId, Name, Description, UnitPrice, StockQuantity, DateAdded, LastUpdated) VALUES (50, 5, 'Toys Product 10', 'Limited edition item.', 173.78, 70, '2025-10-09', '2025-11-19');

-- Insert tags
INSERT INTO Tags (TagId, Name, ProductId) VALUES (1, 'trending', 1);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (2, 'limited', 1);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (3, 'eco-friendly', 1);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (4, 'sale', 2);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (5, 'eco-friendly', 3);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (6, 'new', 3);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (7, 'trending', 4);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (8, 'new', 4);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (9, 'eco-friendly', 5);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (10, 'new', 5);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (11, 'sale', 6);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (12, 'popular', 7);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (13, 'trending', 8);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (14, 'eco-friendly', 8);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (15, 'sale', 8);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (16, 'new', 9);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (17, 'limited', 9);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (18, 'new', 10);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (19, 'limited', 11);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (20, 'eco-friendly', 12);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (21, 'limited', 12);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (22, 'trending', 12);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (23, 'trending', 13);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (24, 'trending', 14);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (25, 'eco-friendly', 14);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (26, 'limited', 15);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (27, 'new', 15);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (28, 'trending', 16);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (29, 'eco-friendly', 17);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (30, 'limited', 17);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (31, 'new', 17);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (32, 'trending', 18);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (33, 'eco-friendly', 19);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (34, 'limited', 19);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (35, 'new', 19);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (36, 'eco-friendly', 20);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (37, 'trending', 20);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (38, 'trending', 21);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (39, 'new', 21);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (40, 'new', 22);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (41, 'sale', 22);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (42, 'eco-friendly', 22);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (43, 'eco-friendly', 23);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (44, 'sale', 23);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (45, 'sale', 24);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (46, 'popular', 25);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (47, 'sale', 26);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (48, 'popular', 27);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (49, 'trending', 27);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (50, 'sale', 27);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (51, 'new', 28);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (52, 'trending', 28);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (53, 'eco-friendly', 28);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (54, 'new', 29);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (55, 'sale', 29);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (56, 'trending', 30);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (57, 'sale', 30);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (58, 'eco-friendly', 31);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (59, 'new', 32);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (60, 'eco-friendly', 33);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (61, 'limited', 33);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (62, 'trending', 34);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (63, 'sale', 34);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (64, 'eco-friendly', 34);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (65, 'limited', 35);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (66, 'sale', 35);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (67, 'trending', 36);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (68, 'eco-friendly', 36);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (69, 'sale', 37);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (70, 'trending', 37);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (71, 'eco-friendly', 37);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (72, 'sale', 38);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (73, 'new', 39);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (74, 'popular', 39);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (75, 'sale', 39);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (76, 'popular', 40);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (77, 'new', 40);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (78, 'eco-friendly', 41);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (79, 'limited', 41);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (80, 'limited', 42);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (81, 'new', 42);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (82, 'limited', 43);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (83, 'trending', 43);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (84, 'popular', 44);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (85, 'trending', 44);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (86, 'popular', 45);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (87, 'limited', 46);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (88, 'popular', 46);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (89, 'new', 46);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (90, 'sale', 47);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (91, 'trending', 47);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (92, 'new', 47);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (93, 'sale', 48);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (94, 'limited', 49);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (95, 'eco-friendly', 49);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (96, 'trending', 49);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (97, 'new', 50);
INSERT INTO Tags (TagId, Name, ProductId) VALUES (98, 'eco-friendly', 50);
